### ISSUE TITLE
Debug python key tracing error with hf_BigBird

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#80]
edited by @ezyang

Repro
```
./torchbench.py --no-skip --python-key -n 1 -k hf_BigBird --devices cuda --float32
```

----

old stuff (this output is no longer master

Output
```
cpu  eval  hf_BigBird                         ERROR:root:unhandled error
Traceback (most recent call last):
  File "./torchbench.py", line 911, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./torchbench.py", line 456, in forward_pass
    def forward_pass(mod, inputs, collect_outputs=True):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2321, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("(batch_size, sequence_length)"))
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1920, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("(batch_size, sequence_length)"))
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1615, in forward
    layer_outputs = layer_module(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1451, in forward
    def forward(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1381, in forward
    self_outputs = self.self(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 435, in forward
    def forward(
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 502, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 502, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 502, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  [Previous line repeated 2 more times]
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 58, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 129, in call_fn
    return inner(*params_flat, *args)
  File "<eval_with_key>.20", line 105, in forward
    unsqueeze__1 = torch.ops.aten.unsqueeze_(detach_36, 2);  detach_36 = None
  File "/home/jansel/pytorch/torch/_ops.py", line 142, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
ERROR
```

Somehow the code produced by python key tracing triggers an error.

cc @Chillee @anijain2305

**Comment by bitfort** [comment]
for 1.13: Try to fix the bug, if we can't easily fix, then silence the warning / error and come back to fix for another release.

**Comment by Chillee** [comment]
It appears that we do some ... hacky things when we call `unsqueeze_`.

```
def f(x):
  out = x.view(4, 3)
  out.unsqueeze_(-1)
  return out

fx_g = make_fx(f)(torch.randn(3, 4))
fx_g(torch.randn(3, 4))
```
errors with
```
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

**Comment by jansel** [comment]
This still fails, but the new error is: `RuntimeError: expected scalar type Half but found Float`

**Comment by jansel** [comment]
If I run in `float32` mode, this becomes:
```
cuda eval  hf_BigBird                         Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.69", line 5, in forward
    unsqueeze_ = _stack0.unsqueeze_(0)
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

**Comment by ezyang** [comment]
@Chillee minimized test case no longer fails on master

**Comment by ezyang** [comment]
Here's what I get on latest:

```
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/torchdynamo/benchmarks$ ./torchbench.py --no-skip --python-k
ey -n 1 -k hf_BigBird --devices cuda --float32                    
cuda eval  hf_BigBird                         ERROR FROM offset=936 filename /scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-
packages/transformers/models/big_bird/modeling_big_bird.py 2172 AssertionError                                                       
========== TorchDynamo Stack Trace ==========                                                                                        
Traceback (most recent call last):                                
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 304, in _convert_frame_assert                                   
    code = transform_code_object(frame.f_code, transform)         
  File "/raid/ezyang/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)                   
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 280, in transform
    tracer.run()
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 1335, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/raid/ezyang/torchdynamo/torchdynamo/output_graph.py", line 290, in compile_subgraph
    pass1.foreach(stack_values)
  File "/raid/ezyang/torchdynamo/torchdynamo/codegen.py", line 175, in foreach
    self(i)
  File "/raid/ezyang/torchdynamo/torchdynamo/codegen.py", line 157, in __call__
    output.extend(value.reconstruct(self))
  File "/raid/ezyang/torchdynamo/torchdynamo/variables/dicts.py", line 297, in reconstruct
    assert result[-1].opname == "BUILD_CONST_KEY_MAP"
AssertionError
```

and without float32

```
Traceback (most recent call last):                                                                                                   
  File "/raid/ezyang/torchdynamo/torchdynamo/optimizations/python_key.py", line 102, in run_node                                     
    result = super().run_node(n)                                                                                                     
  File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 154, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)                                                                               
  File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 226, in call_function                
    return target(*args, **kwargs)                                                                                                   
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 206, in __torch_dispatch__                        
    return proxy_call(func_overload, args, kwargs)           
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 105, in proxy_call                                
    inner_res = func_overload(*pytree.tree_map(unwrap_elem, args), **pytree.tree_map(unwrap_elem, kwargs))
  File "/raid/ezyang/pytorch-scratch2/torch/_ops.py", line 49, in __call__                                                           
    return self._op(*args, **kwargs or {})                                                                                           
RuntimeError: expected scalar type Half but found Float    
```

I'll check on the without float32 error but the first error looks like a dynamo problem

**Comment by mlazos** [comment]
> Here's what I get on latest:
> 
> ```
> (/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/torchdynamo/benchmarks$ ./torchbench.py --no-skip --python-k
> ey -n 1 -k hf_BigBird --devices cuda --float32                    
> cuda eval  hf_BigBird                         ERROR FROM offset=936 filename /scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-
> packages/transformers/models/big_bird/modeling_big_bird.py 2172 AssertionError                                                       
> ========== TorchDynamo Stack Trace ==========                                                                                        
> Traceback (most recent call last):                                
>   File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 304, in _convert_frame_assert                                   
>     code = transform_code_object(frame.f_code, transform)         
>   File "/raid/ezyang/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
>     transformations(instructions, code_options)                   
>   File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 280, in transform
>     tracer.run()
>   File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run
>     and self.step()
>   File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step
>     getattr(self, inst.opname)(inst)
>   File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 1335, in RETURN_VALUE
>     self.output.compile_subgraph(self)
>   File "/raid/ezyang/torchdynamo/torchdynamo/output_graph.py", line 290, in compile_subgraph
>     pass1.foreach(stack_values)
>   File "/raid/ezyang/torchdynamo/torchdynamo/codegen.py", line 175, in foreach
>     self(i)
>   File "/raid/ezyang/torchdynamo/torchdynamo/codegen.py", line 157, in __call__
>     output.extend(value.reconstruct(self))
>   File "/raid/ezyang/torchdynamo/torchdynamo/variables/dicts.py", line 297, in reconstruct
>     assert result[-1].opname == "BUILD_CONST_KEY_MAP"
> AssertionError
> ```
> 
> and without float32
> 
> ```
> Traceback (most recent call last):                                                                                                   
>   File "/raid/ezyang/torchdynamo/torchdynamo/optimizations/python_key.py", line 102, in run_node                                     
>     result = super().run_node(n)                                                                                                     
>   File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 154, in run_node
>     return getattr(self, n.op)(n.target, args, kwargs)                                                                               
>   File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 226, in call_function                
>     return target(*args, **kwargs)                                                                                                   
>   File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 206, in __torch_dispatch__                        
>     return proxy_call(func_overload, args, kwargs)           
>   File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 105, in proxy_call                                
>     inner_res = func_overload(*pytree.tree_map(unwrap_elem, args), **pytree.tree_map(unwrap_elem, kwargs))
>   File "/raid/ezyang/pytorch-scratch2/torch/_ops.py", line 49, in __call__                                                           
>     return self._op(*args, **kwargs or {})                                                                                           
> RuntimeError: expected scalar type Half but found Float    
> ```
> 
> I'll check on the without float32 error but the first error looks like a dynamo problem

https://github.com/pytorch/torchdynamo/pull/624 should fix the map issue

**Comment by ezyang** [comment]
After #624, float runs with no problems, but half still fails with python key. Maybe some sort of autocast related issue.

**Comment by eellison** [comment]
I ran this benchmark with a FakeTensorCrossRef mode and didnt get any errors, so it's likely a ProxyTensor issue. we can do a similar ProxyTensor crossref test.

**Comment by ezyang** [comment]
we're wondering if this bug still exists if you use aot autograd instead of python key. Stock aot autograd skips out, need to patch in https://github.com/pytorch/pytorch/pull/83248 which is python key replacement

**Comment by ezyang** [comment]
It looks like BigBird still fails, because the graph has a metadata mutating operation on an input argument to a graph

```
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 749, in functional_call                                    
    out = mod(*args[params_len:], **kwargs)                             
  File "/raid/ezyang/pytorch-scratch2/torch/fx/graph_module.py", line 655, in call_wrapped                                                       
    return self._wrapped_call(self, *args, **kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/graph_module.py", line 277, in __call__                                                           
    raise e                                                                                                                                      
  File "/raid/ezyang/pytorch-scratch2/torch/fx/graph_module.py", line 267, in __call__                                                           
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]                                                                  
  File "/raid/ezyang/pytorch-scratch2/torch/fx/_symbolic_trace.py", line 693, in module_call_wrapper                                             
    return self.call_module(mod, forward, args, kwargs)                                                                                          
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 318, in call_module                                           
    return forward(*args, **kwargs)                                     
  File "/raid/ezyang/pytorch-scratch2/torch/fx/_symbolic_trace.py", line 686, in forward          
    return _orig_module_call(mod, *args, **kwargs)                      
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/module.py", line 1186, in _call_impl                                                      
    return forward_call(*input, **kwargs)                                                                                                        
  File "<eval_with_key>.7", line 5, in forward                                                                                                   
    unsqueeze_ = _stack0.unsqueeze_(0)                                  
  File "/raid/ezyang/pytorch-scratch2/torch/utils/_python_dispatch.py", line 74, in wrapped                                                      
    return f(self, *args, **kwargs)                                                                                                              
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 402, in __torch_dispatch__                                    
    return proxy_call(self, func_overload, args, kwargs)                                                                                         
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 175, in proxy_call                                            
    inner_res = func_overload(*pytree.tree_map(unwrap_elem, args), **pytree.tree_map(unwrap_elem, kwargs))
  File "/raid/ezyang/pytorch-scratch2/torch/_ops.py", line 60, in __call__                                                                       
    return self._op(*args, **kwargs or {})                                                                                                       
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().                                                     
```

failing call:

```
aten.unsqueeze_.default (Proxy(arg0_1), 0) {}  
```

**Comment by ezyang** [comment]
cc @bdhirsh

**Comment by anijain2305** [comment]
Setting `functorch.compile.config.use_functionalize = True` works.

The issue seems to be in TorchDynamo functionalization. As we plan to move to Dispatcher functionalization, I can just do a try..catch for TorchDynamo functionalization.

**Comment by ezyang** [comment]
Without functionalization, if we allow resizing detached tensors (@albanD has approved this), bigbird now gets through tracing and just fails accuracy check

```
ezyang@devfair040:/scratch/ezyang/torchdynamo$ ./benchmarks/torchbench.py --no-skip --accuracy-aot-nop -n 1 -k hf_BigBird --devices cuda --training
cuda train hf_BigBird                         Accuracy failed for key name bert.embeddings.token_type_embeddings.weight.grad
INCORRECT
```

**Comment by ezyang** [comment]
This is now obsolete as python key is being deleted.
